---
- name: install php7
  apt: name={{ item }} state=present install_recommends=no
  with_items:
  - php7.0
  - php-cli
  - php-curl
  - php-gd                  # cover generation
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - libapache2-mod-php7.0
  - php-apcu
  - php-intl                # UTF-8-MAC, CPS, platform only
  - php-imagick             # cmyk=>rgb 변환
  - php-bcmath              # binary log 분석기

- name: install dependencies
  apt: name={{ item }} state=present install_recommends=no
  with_items:
  - zip                     # download API
  - imagemagick             # 이미지 처리
  - gifsicle                # 이미지 최적화
  - jpegoptim
  - optipng
  - poppler-utils

# php.ini apache
- name: configure apache2/php.ini
  ini_file:
    dest=/etc/php/7.0/apache2/php.ini
    option="{{ item.option }}"
    section="{{ item.section }}"
    value="{{ item.value }}"
  with_items: "{{ php_apache_config }}"

# php.ini cli
- name: configure cli/php.ini
  ini_file:
    dest=/etc/php/7.0/cli/php.ini
    option="{{ item.option }}"
    section="{{ item.section }}"
    value="{{ item.value }}"
  with_items: "{{ php_cli_config }}"

- name: restart apache
  service: name=apache2 state=restarted
