---
- name: install apache
  apt: name=apache2 update_cache=yes state=present install_recommends=no

- name: enable apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - headers
    - ssl

- name: setup apache conf
  template: src=intranet.conf dest=/etc/apache2/sites-available/intranet.conf
  notify:
   - restart apache

- name: disable default site
  command: "a2dissite {{ item }}"
  args:
    removes: /etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
   - 000-default

- name: enable apache site
  command: "a2ensite {{ item }}"
  args:
    creates: /etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
   - intranet
